module.exports.context = {
  colors: {
    building: 'rgb(234, 234, 234)',
    chrome: 'rgb(218, 219, 223)',
    locality: 'rgb(92, 92, 92)',
    neighborhood: 'rgb(118, 118, 118)',
    road_label: 'rgb(143, 143, 143)',
    road_label_light: 'rgb(156, 156, 156)',
    halo: 'rgb(224, 224, 224)',
    halo_light: 'rgb(244, 244, 244)',
    ground_dark: 'rgb(226, 223, 218)',
    ground_light: 'rgb(250, 252, 251)',
    irrigated: 'rgb(178, 223, 138)',
    forest: 'rgb(51, 160, 44)',
    other_vegetation: 'rgb(178, 223, 138)',
    trail: 'rgb(191, 56, 63)',
    watershed_highlight: 'rgb(255, 254, 253)',
    water_light: 'rgb(148, 220, 251)',
    water_dark: 'rgb(89, 132, 151)',
    waterLabel: 'rgb(66, 99, 115)',
  }
};

module.exports.template = {
  "version": 8,
  "name": "Muddy_Branch_Greenway_Trail_Map",
  "sources": {
    "protomaps": {
      "attribution": "<a href=\"https://github.com/protomaps/basemaps\">Protomaps</a>",
      "type": "vector",
      "url": "pmtiles://assets/Muddy_Branch_Greenway_Trail_Map/muddy_branch_area.pmtiles"
    },
    "muddy_branch_relation": {
      "type": "geojson",
      "data": "assets/Muddy_Branch_Greenway_Trail_Map/muddy_branch_relation.geojson",
      "attribution": "© <a href=\"https://openstreetmap.org\">OpenStreetMap</a>"
    },
    "montgomery_county_dem": {
      "type": "raster-dem",
      "encoding": "terrarium",
      "url": "https://tiles.stadiamaps.com/data/terrarium.json",
      "tileSize": 256
    },
    "muddy_branch_watershed": {
      "type": "geojson",
      "data": "assets/Muddy_Branch_Greenway_Trail_Map/muddy_branch_watershed.geojson"
    }
  },
  "sprite": "https://mizmay.github.io/muddy_branch_maps/assets/Muddy_Branch_Greenway_Trail_Map/sprites/sprites",
  "glyphs": "https://mizmay.github.io/muddy_branch_maps/assets/Muddy_Branch_Greenway_Trail_Map/fonts/{fontstack}/{range}.pbf",
  "layers": [
    "background",
    "hillshade",
    "muddy_branch_watershed",
    "landuse_park",
    "landuse_aerodrome",
    "roads_runway",
    "roads_taxiway",
    "landuse_runway",
    "water",
    "water_waterway",
    "landuse_pedestrian",
    "landuse_pier",
    "roads_tunnels_other_casing",
    "roads_tunnels_minor_casing",
    "roads_tunnels_link_casing",
    "roads_tunnels_major_casing",
    "roads_tunnels_highway_casing",
    "roads_tunnels_other",
    "roads_tunnels_minor",
    "roads_tunnels_link",
    "roads_tunnels_major",
    "roads_tunnels_highway",
    "buildings",
    "roads_pier",
    "roads_minor_service_casing",
    "roads_minor_casing",
    "roads_link_casing",
    "roads_major_casing_late",
    "roads_highway_casing_late",
    "roads_other",
    "roads_link",
    "roads_minor_service",
    "roads_minor",
    "roads_major_casing_early",
    "roads_major",
    "roads_highway_casing_early",
    "roads_highway",
    "roads_rail",
    "muddy-branch-trail",
    "muddy_branch_parking",
    "roads_bridges_other_casing",
    "roads_bridges_link_casing",
    "roads_bridges_minor_casing",
    "roads_bridges_major_casing",
    "roads_bridges_other",
    "roads_bridges_minor",
    "roads_bridges_link",
    "roads_bridges_major",
    "roads_bridges_highway_casing",
    "roads_bridges_highway",
    "water_waterway_label",
    "roads_labels_minor",
    "water_label_lakes",
    "roads_labels_major",
    "places_subplace",
    "places_locality",
    "muddy_branch_access"
  ],
  "id": "h7f7a74"
};
